name: CD

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environnement cible"
        required: true
        default: "production"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Connexion à GitHub (ghcr.io)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extraire nom en minuscules et SHA court
        id: meta
        run: |
          echo "repo=${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"
          echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build et Push sur GHCR avec 3 tags
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.meta.outputs.repo }}:latest
            ghcr.io/${{ steps.meta.outputs.repo }}:${{ steps.meta.outputs.short_sha }}
            ghcr.io/${{ steps.meta.outputs.repo }}:1.0.0

  deploy:
    needs: build-and-push
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: production
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Connexion à Github
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extraire nom du repo
        id: meta
        run: echo "repo=${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

      - name: Deploiement, healthcheck (3 retries) et rollback
        run: |
          chmod +x ./deploy/deploy.sh
          IMAGE="ghcr.io/${{ steps.meta.outputs.repo }}:latest"
          docker network create app-net 2>/dev/null || true
          docker stop redis 2>/dev/null || true
          docker rm redis 2>/dev/null || true
          docker run -d --name redis --network app-net -p 6379:6379 redis:7-alpine
          sleep 2
          
          docker pull "$IMAGE"
          ./deploy/deploy.sh "$IMAGE" "$IMAGE"
